services:
  app:
    image: waxlabs/notifications:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app:Z
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
